SLOTH: ProductCoefficient Class Reference
ProductCoefficient Class Reference
Define a product of FunctionCoefficient objects as a FunctionCoefficient.
#include <ProductFunctionCoefficients.hpp>
Public Member Functions
ProductCoefficient ()=default
ProductCoefficient (std::initializer_list< FunctionCoefficient * > coeffs)
Build a FunctionCoefficient as the product of several FunctionCoefficients.
void set_time (double time) override
Set time for all FunctionCoefficients.
virtual ~ProductCoefficient ()=default
Public Member Functions inherited from FunctionCoefficient
double eval_f (const std::span< const double > &input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the coefficient.
double eval_f (const std::span< const double > &input_vector, const std::span< const double > &exp_input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the coefficient.
double eval_f (const std::span< const double > &input_vector, std::optional< int > dimension=std::nullopt)
Evaluates the coefficient.
double eval_gradient (const int i, const std::span< const double > &input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the component i of the gradient.
double eval_gradient (const int i, const std::span< const double > &input_vector, const std::span< const double > &exp_input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the component i of the gradient.
double eval_gradient (const int i, const std::span< const double > &input_vector, std::optional< int > dimension=std::nullopt)
Evaluates the component i of the gradient.
double eval_hessian (const int i, const int j, const std::span< const double > &input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
double eval_hessian (const int i, const int j, const std::span< const double > &input_vector, const std::span< const double > &exp_input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
double eval_hessian (const int i, const int j, const std::span< const double > &input_vector, std::optional< int > dimension=std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
FunctionCoefficient ()
Construct a new FunctionCoefficient::FunctionCoefficient object.
virtual ~FunctionCoefficient ()=default
Protected Member Functions
std::function< double(const std::span< const double > &, const std::span< const double > &, const std::span< const double > &, const unsigned int dimension)> F () final
Compute the value of the coefficient as a summation of the value of coefficients.
std::function< std::vector< double >const std::span< const double > &, const std::span< const double > &, const std::span< const double > &, const unsigned int dimension)> GradientF () final
Gradient.
std::function< std::vector< double >const std::span< const double > &, const std::span< const double > &, const std::span< const double > &, const unsigned int dimension)> HessianF () final
Hessian.
Additional Inherited Members
Protected Attributes inherited from FunctionCoefficient
double time_
Detailed Description
Define a product of FunctionCoefficient objects as a FunctionCoefficient.
Remarks
This suggest that all FunctionCoefficient share the same variables...
Definition at line 47 of file ProductFunctionCoefficients.hpp.
Constructor & Destructor Documentation
ProductCoefficient() [1/2]
ProductCoefficient::ProductCoefficient (std::initializer_list< FunctionCoefficient * > coeffs) explicit
Build a FunctionCoefficient as the product of several FunctionCoefficients.
Template Parameters
Args
Definition at line 49 of file ProductFunctionCoefficients.cpp.
ProductCoefficient() [2/2]
ProductCoefficient::ProductCoefficient () default
~ProductCoefficient()
virtual ProductCoefficient::~ProductCoefficient () virtual default
Member Function Documentation
F()
std::function< double(const std::span< const double > &, const std::span< const double > &, const std::span< const double > &, const unsigned int dimension)> ProductCoefficient::F () final protected virtual
Compute the value of the coefficient as a summation of the value of coefficients.
Returns
std::function<double(const std::span<const double>&, const std::span<const double>&, const unsigned int dimension)>
Implements FunctionCoefficient.
Definition at line 60 of file ProductFunctionCoefficients.cpp.
Referenced by GradientF(), and HessianF().
GradientF()
std::function< std::vector< double >const std::span< const double > &, const std::span< const double > &, const std::span< const double > &, const unsigned int dimension)> ProductCoefficient::GradientF () final protected virtual
Gradient.
Returns
std::function<std::vector<double>(const std::span<const double>&,const std::span<const double>&, const unsigned int dimension)>
Implements FunctionCoefficient.
Definition at line 84 of file ProductFunctionCoefficients.cpp.
References F().
HessianF()
std::function< std::vector< double >const std::span< const double > &, const std::span< const double > &, const std::span< const double > &, const unsigned int dimension)> ProductCoefficient::HessianF () final protected virtual
Hessian.
Remarks
Hessian matrix stored in vector : H(i,j)->H(i*n+j)
Returns
std::function<std::vector<double>(const std::span<const double>&,const std::span<const double>&, const unsigned int dimension)>
Implements FunctionCoefficient.
Definition at line 116 of file ProductFunctionCoefficients.cpp.
References F().
set_time()
void ProductCoefficient::set_time (double time) override virtual
Set time for all FunctionCoefficients.
Parameters
time
Reimplemented from FunctionCoefficient.
Definition at line 166 of file ProductFunctionCoefficients.cpp.
References FunctionCoefficient::time_.
The documentation for this class was generated from the following files:
ProductFunctionCoefficients.hpp
ProductFunctionCoefficients.cpp