SLOTH: Parameters Class Reference
Parameters Class Reference
#include <Parameters.hpp>
Public Member Functions
template<typename T >
T get_param_value (const std::string &name) const
template<typename T >
T get_param_value_or_default (const std::string &name, T default_value) const
std::optional< Parameter > get_parameter (const std::string &name) const
Return the parameter associated to the given name.
int get_size () const
Return the size of a Parameters.
std::vector< Parameter > get_vector () const
Return a vector of Parameter.
bool has_parameter (const std::string &param_name) const
Search a parameter by its name.
Parameters operator+ (const Parameter &param) const
Add a parameter inside a Parameters. If param already exists, the given parameters overwrites the existing one.
Parameters operator+ (const Parameters &params) const
Add two Parameters with a priority given to the second Parameters to overwrite Parameter objets in the first Parameters if already exist.
Parameters operator- (const Parameter &param) const
Remove a parameter inside a Parameters if exists.
Parameters (const std::vector< Parameter > &vect_params)
Construct a new Parameters:: Parameters object.
template<typename... Args>
requires (ParameterType< Args > &&...) explicit Parameters(Args &&... args)
virtual ~Parameters ()=default
Detailed Description
Definition at line 46 of file Parameters.hpp.
Constructor & Destructor Documentation
Parameters()
Parameters::Parameters (const std::vector< Parameter > & vect_params) explicit
Construct a new Parameters:: Parameters object.
Parameters
vect_params
Definition at line 45 of file Parameters.cpp.
Referenced by operator+(), and operator-().
~Parameters()
virtual Parameters::~Parameters () virtual default
Member Function Documentation
get_param_value()
template<typename T > T Parameters::get_param_value (const std::string & name) const
Referenced by SolverUMFPACK::create_solver(), PrecondHypreILU::create_solver(), PrecondHypreSmoother::create_solver(), PrecondHypreBoomerAMG::create_solver(), PrecondHypreDiagScale::create_solver(), SolverHyprePCG::create_solver(), SolverHypreGMRES::create_solver(), SolverHypreFGMRES::create_solver(), PrecondDSmoother::create_solver(), SolverBICGSTAB::create_solver(), SolverMINRES::create_solver(), SolverCG::create_solver(), SolverGMRES::create_solver(), SolverNewton::create_solver(), and SolverLBFGS::create_solver().
get_param_value_or_default()
template<typename T > T Parameters::get_param_value_or_default (const std::string & name, T default_value) const
Referenced by SolverUMFPACK::create_solver(), PrecondHypreILU::create_solver(), PrecondHypreSmoother::create_solver(), PrecondHypreBoomerAMG::create_solver(), SolverHyprePCG::create_solver(), SolverHypreGMRES::create_solver(), SolverHypreFGMRES::create_solver(), PrecondDSmoother::create_solver(), SolverBICGSTAB::create_solver(), SolverMINRES::create_solver(), SolverCG::create_solver(), SolverGMRES::create_solver(), SolverNewton::create_solver(), and SolverLBFGS::create_solver().
get_parameter()
std::optional< Parameter > Parameters::get_parameter (const std::string & name) const
Return the parameter associated to the given name.
Parameters
name
Returns
Parameter
Definition at line 82 of file Parameters.cpp.
get_size()
int Parameters::get_size () const
Return the size of a Parameters.
Template Parameters
Args
Returns
in
Definition at line 74 of file Parameters.cpp.
get_vector()
std::vector< Parameter > Parameters::get_vector () const
Return a vector of Parameter.
Template Parameters
Args
Returns
std::vector<Parameter>
Definition at line 53 of file Parameters.cpp.
Referenced by operator+(), and operator-().
has_parameter()
bool Parameters::has_parameter (const std::string & param_name) const
Search a parameter by its name.
Parameters
param_name
Returns
true
false
Definition at line 62 of file Parameters.cpp.
operator+() [1/2]
Parameters Parameters::operator+ (const Parameter & param) const
Add a parameter inside a Parameters. If param already exists, the given parameters overwrites the existing one.
Parameters
param
Returns
Parameters
Definition at line 114 of file Parameters.cpp.
References get_vector(), and Parameters().
operator+() [2/2]
Parameters Parameters::operator+ (const Parameters & params) const
Add two Parameters with a priority given to the second Parameters to overwrite Parameter objets in the first Parameters if already exist.
Parameters
params
Returns
Parameters
Definition at line 134 of file Parameters.cpp.
References get_vector(), and Parameters().
operator-()
Parameters Parameters::operator- (const Parameter & param) const
Remove a parameter inside a Parameters if exists.
Parameters
param
Returns
Parameters
Definition at line 97 of file Parameters.cpp.
References get_vector(), and Parameters().
requires()
template<typename... Args> Parameters::requires (ParameterType< Args > && ...) &&
The documentation for this class was generated from the following files:
Parameters.hpp
Parameters.cpp