SLOTH: FunctionCoefficient Class Reference
FunctionCoefficient Class Reference abstract
Base class defining analytical expression, first and second derivatives of a Coefficient.
#include <FunctionCoefficient.hpp>
Public Member Functions
double eval_f (const std::span< const double > &input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the coefficient.
double eval_f (const std::span< const double > &input_vector, const std::span< const double > &exp_input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the coefficient.
double eval_f (const std::span< const double > &input_vector, std::optional< int > dimension=std::nullopt)
Evaluates the coefficient.
double eval_gradient (const int i, const std::span< const double > &input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the component i of the gradient.
double eval_gradient (const int i, const std::span< const double > &input_vector, const std::span< const double > &exp_input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the component i of the gradient.
double eval_gradient (const int i, const std::span< const double > &input_vector, std::optional< int > dimension=std::nullopt)
Evaluates the component i of the gradient.
double eval_hessian (const int i, const int j, const std::span< const double > &input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
double eval_hessian (const int i, const int j, const std::span< const double > &input_vector, const std::span< const double > &exp_input_vector, const std::span< const double > &auxiliary_vector, std::optional< int > dimension=std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
double eval_hessian (const int i, const int j, const std::span< const double > &input_vector, std::optional< int > dimension=std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
FunctionCoefficient ()
Construct a new FunctionCoefficient::FunctionCoefficient object.
virtual void set_time (double time)
Update the time associated with the coefficient.
virtual ~FunctionCoefficient ()=default
Protected Member Functions
virtual std::function< double(const std::span< const double > &values, const std::span< const double > &exp_values, const std::span< const double > &aux_values, const unsigned int dimension)> F ()=0
virtual std::function< std::vector< double > const std::span< const double > &values, const std::span< const double > &exp_values, const std::span< const double > &aux_values, const unsigned int dimension)> GradientF ()=0
virtual std::function< std::vector< double > const std::span< const double > &values, const std::span< const double > &exp_values, const std::span< const double > &aux_values, const unsigned int dimension)> HessianF ()=0
Protected Attributes
double time_
Detailed Description
Base class defining analytical expression, first and second derivatives of a Coefficient.
Definition at line 45 of file FunctionCoefficient.hpp.
Constructor & Destructor Documentation
FunctionCoefficient()
FunctionCoefficient::FunctionCoefficient ()
Construct a new FunctionCoefficient::FunctionCoefficient object.
Definition at line 47 of file FunctionCoefficient.cpp.
~FunctionCoefficient()
virtual FunctionCoefficient::~FunctionCoefficient () virtual default
Member Function Documentation
eval_f() [1/3]
double FunctionCoefficient::eval_f (const std::span< const double > & input_vector, const std::span< const double > & auxiliary_vector, std::optional< int > dimension = std::nullopt)
Evaluates the coefficient.
Remarks
Work for Implicit/Explict coefficients with auxiliary variables and Semi-implicit coefficients without auxiliary variables
The coefficient is computed from the current and auxiliary (explicit) variables.
Parameters
input_vector Values of the current variables.
auxiliary_vector Values of the auxiliary variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the coefficient.
Definition at line 81 of file FunctionCoefficient.cpp.
References F().
eval_f() [2/3]
double FunctionCoefficient::eval_f (const std::span< const double > & input_vector, const std::span< const double > & exp_input_vector, const std::span< const double > & auxiliary_vector, std::optional< int > dimension = std::nullopt)
Evaluates the coefficient.
The coefficient is computed from the current and auxiliary variables.
Parameters
input_vector Values of the current variables.
exp_input_vector Values of the previous variables.
auxiliary_vector Values of the auxiliary variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the coefficient.
Definition at line 101 of file FunctionCoefficient.cpp.
References F().
eval_f() [3/3]
double FunctionCoefficient::eval_f (const std::span< const double > & input_vector, std::optional< int > dimension = std::nullopt)
Evaluates the coefficient.
The coefficient is computed from the current variables.
Parameters
input_vector Values of the current variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the coefficient.
Definition at line 59 of file FunctionCoefficient.cpp.
References F().
eval_gradient() [1/3]
double FunctionCoefficient::eval_gradient (const int i, const std::span< const double > & input_vector, const std::span< const double > & auxiliary_vector, std::optional< int > dimension = std::nullopt)
Evaluates the component i of the gradient.
Remarks
Work for Implicit/Explict coefficients with auxiliary variables and Semi-implicit coefficients without auxiliary variables
The gradient is computed from the current and auxiliary (explicit) variables.
Parameters
i index of the gradient .
input_vector Values of the current variables.
auxiliary_vector Values of the auxiliary variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the gradient component i.
Definition at line 143 of file FunctionCoefficient.cpp.
References GradientF().
eval_gradient() [2/3]
double FunctionCoefficient::eval_gradient (const int i, const std::span< const double > & input_vector, const std::span< const double > & exp_input_vector, const std::span< const double > & auxiliary_vector, std::optional< int > dimension = std::nullopt)
Evaluates the component i of the gradient.
The gradient is computed from the current and auxiliary variables.
Parameters
i index of the gradient .
input_vector Values of the current variables.
exp_input_vector Values of the previous variables.
auxiliary_vector Values of the auxiliary variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the gradient component i.
Definition at line 164 of file FunctionCoefficient.cpp.
References GradientF().
eval_gradient() [3/3]
double FunctionCoefficient::eval_gradient (const int i, const std::span< const double > & input_vector, std::optional< int > dimension = std::nullopt)
Evaluates the component i of the gradient.
The gradient is computed from the current variables.
Parameters
i index of the gradient .
input_vector Values of the current variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the gradient component i.
Definition at line 120 of file FunctionCoefficient.cpp.
References GradientF().
eval_hessian() [1/3]
double FunctionCoefficient::eval_hessian (const int i, const int j, const std::span< const double > & input_vector, const std::span< const double > & auxiliary_vector, std::optional< int > dimension = std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
Remarks
Work for Implicit/Explict coefficients with auxiliary variables and Semi-implicit coefficients without auxiliary variables
The Hessian is computed from the current and auxiliary (explicit) variables and returned as a flattened array. The component is accessed using row-major ordering.
Parameters
i Row index of the Hessian matrix.
j Column index of the Hessian matrix.
input_vector Values of the current variables.
auxiliary_vector Values of the auxiliary variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the Hessian component (i, j).
Definition at line 212 of file FunctionCoefficient.cpp.
References HessianF().
eval_hessian() [2/3]
double FunctionCoefficient::eval_hessian (const int i, const int j, const std::span< const double > & input_vector, const std::span< const double > & exp_input_vector, const std::span< const double > & auxiliary_vector, std::optional< int > dimension = std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
The Hessian is computed from the current and auxiliary variables and returned as a flattened array. The component is accessed using row-major ordering.
Parameters
i Row index of the Hessian matrix.
j Column index of the Hessian matrix.
input_vector Values of the current variables.
exp_input_vector Values of the previous variables.
auxiliary_vector Values of the auxiliary variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the Hessian component (i, j).
Definition at line 238 of file FunctionCoefficient.cpp.
References HessianF().
eval_hessian() [3/3]
double FunctionCoefficient::eval_hessian (const int i, const int j, const std::span< const double > & input_vector, std::optional< int > dimension = std::nullopt)
Evaluates the (i,j) component of the Hessian matrix.
The Hessian is computed from the current variables and returned as a flattened array. The component is accessed using row-major ordering.
Parameters
i Row index of the Hessian matrix.
j Column index of the Hessian matrix.
input_vector Values of the current variables.
dimension Optional spatial dimension (use -1 if not specified).
Returns
Value of the Hessian component (i, j).
Definition at line 185 of file FunctionCoefficient.cpp.
References HessianF().
F()
virtual std::function< double(const std::span<const double>& values, const std::span<const double>& exp_values, const std::span<const double>& aux_values, const unsigned int dimension)> FunctionCoefficient::F () protected pure virtual
Implemented in SumCoefficient, ProductCoefficient, ExprTkCoefficient, ConstantCoefficient, GradientEnergy, Log, H, Fw, and W.
Referenced by eval_f().
GradientF()
virtual std::function<std::vector<double> const std::span<const double>& values, const std::span<const double>& exp_values, const std::span<const double>& aux_values, const unsigned int dimension)> FunctionCoefficient::GradientF () protected pure virtual
Implemented in SumCoefficient, ProductCoefficient, ExprTkCoefficient, ConstantCoefficient, GradientEnergy, Log, H, Fw, and W.
Referenced by eval_gradient().
HessianF()
virtual std::function<std::vector<double> const std::span<const double>& values, const std::span<const double>& exp_values, const std::span<const double>& aux_values, const unsigned int dimension)> FunctionCoefficient::HessianF () protected pure virtual
Implemented in SumCoefficient, ProductCoefficient, ExprTkCoefficient, ConstantCoefficient, GradientEnergy, Log, H, Fw, and W.
Referenced by eval_hessian().
set_time()
void FunctionCoefficient::set_time (double time) virtual
Update the time associated with the coefficient.
Reimplemented in SumCoefficient, and ProductCoefficient.
Definition at line 252 of file FunctionCoefficient.cpp.
References time_.
Member Data Documentation
time_
double FunctionCoefficient::time_ protected
Definition at line 47 of file FunctionCoefficient.hpp.
Referenced by set_time(), ProductCoefficient::set_time(), and SumCoefficient::set_time().
The documentation for this class was generated from the following files:
FunctionCoefficient.hpp
FunctionCoefficient.cpp