SLOTH: SolverBICGSTAB Class Reference
SolverBICGSTAB Class Reference
#include <ISolverBase.hpp>
Public Member Functions
std::shared_ptr< mfem::BiCGSTABSolver > create_solver (const Parameters &params) override
Create a iterative solver based of the SolverType and a list of Parameters.
SolverBICGSTAB ()
~SolverBICGSTAB ()
Public Member Functions inherited from SolverBase< mfem::BiCGSTABSolver, IterativeSolverType >
std::string get_description ()
virtual ~SolverBase ()=default
Additional Inherited Members
Public Attributes inherited from SolverBase< mfem::BiCGSTABSolver, IterativeSolverType >
std::string solver_description_
Detailed Description
Definition at line 37 of file ISolverBase.hpp.
Constructor & Destructor Documentation
SolverBICGSTAB()
SolverBICGSTAB::SolverBICGSTAB () inline
Definition at line 39 of file ISolverBase.hpp.
~SolverBICGSTAB()
SolverBICGSTAB::~SolverBICGSTAB () inline
Definition at line 42 of file ISolverBase.hpp.
Member Function Documentation
create_solver()
std::shared_ptr< mfem::BiCGSTABSolver > SolverBICGSTAB::create_solver (const Parameters & params) override virtual
Create a iterative solver based of the SolverType and a list of Parameters.
Parameters
SOLVER
params
Returns
std::shared_ptr<mfem::IterativeSolver>
Implements SolverBase< mfem::BiCGSTABSolver, IterativeSolverType >.
Definition at line 45 of file ISolverBase.cpp.
References BICGSTABDefaultConstant::abs_tol, SlothInfo::debug(), SolverBase< mfem::BiCGSTABSolver, IterativeSolverType >::get_description(), Parameters::get_param_value(), Parameters::get_param_value_or_default(), BICGSTABDefaultConstant::iter_max, NewtonDefaultConstant::iterative_mode, BICGSTABDefaultConstant::iterative_mode, NewtonDefaultConstant::print_level, BICGSTABDefaultConstant::print_level, BICGSTABDefaultConstant::rel_tol, SolverBase< mfem::BiCGSTABSolver, IterativeSolverType >::solver_description_, Verbose, and verbose_at_least().
Referenced by SlothSolver::get_value().
The documentation for this class was generated from the following files:
ISolverBase.hpp
ISolverBase.cpp